name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker image tag
      id: docker_tag
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: |
        docker build . --file nginx/Dockerfile --tag ghcr.io/${{ github.repository }}/website:${{ env.TAG }}
        docker tag ghcr.io/${{ github.repository }}/website:${{ env.TAG }} ghcr.io/${{ github.repository }}/website:latest

    - name: Push the Docker image
      env:
        CR_PAT: ${{ secrets.GHCR_PAT }}
      run: |
        echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/${{ github.repository }}/website:${{ env.TAG }}
        docker push ghcr.io/${{ github.repository }}/website:latest
